### ISSUE TITLE
Broken in WP 4.3

### ISSUE THREAD

**Issue by nobleclem** [bu-ist/bu-navigation#13]
Sorry for duplicating.  Want to make sure you are aware of the problem and a potential quick fix solution:
https://wordpress.org/support/topic/broken-in-43?replies=2#post-7318803

**Comment by awbauer** [comment]
Thank you for the report @nobleclem. Could you submit a pull request for review?

**Comment by nobleclem** [comment]
Done: https://github.com/bu-ist/bu-navigation/pull/14

**Comment by awbauer** [comment]
Thank you, very much appreciated.

**Comment by awbauer** [comment]
Looks good @nobleclem, packaging for release now.
