### ISSUE TITLE
Adaptive navigation issue with bu_navigation_gather_sections()

### ISSUE THREAD

**Issue by awbauer** [bu-ist/bu-navigation#16]
Widget area:
4th-level pages with hidden children display the incorrect section in the widget title. 

Example:
**On the Old Editions page, navigation widget title should show `Faculty`** 
Instead, it shows `Legal History`
- Home
  - Faculty
    - Legal History
      - Old Editions
         - _Book Reference_ [hidden in nav]
      - Manuscript Listings
      - Bibliography
  - Admissions
  - Careers

Issue boils down to `bu_navigation_gather_sections` classifying the `Old Editions` page as a section, without checking to see if any of its children are visible in the navigation.

See discussion in Slack: https://buweb.slack.com/archives/law-website/p1450124082000485
ServiceNow ticket: DFCT0011841

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#law-website**. [View the logs :arrow_right:](https://buweb.slack.com/archives/law-website/p1450126278000519)

**Comment by awbauer** [comment]
Added test case in 547e1b10e

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#wp-dev**. [View the logs :arrow_right:](https://buweb.slack.com/archives/wp-dev/p1450387630000519)
