### ISSUE TITLE
Hidden section still showing parent page in navigation widget (set to adaptive navigation)

### ISSUE THREAD

**Issue by malakhi** [bu-ist/bu-navigation#19]
This is showing up for the Law School site. Here is what I know:

- Adaptive navigation is set for the navigation widget throughout the website
- The [parent page](http://nm.cms-devl.bu.edu/law/current-students/career-development/employment-sectors/clerkships/alumni-clerk-directory/) and all [child pages](http://nm.cms-devl.bu.edu/law/current-students/career-development/employment-sectors/clerkships/alumni-clerk-directory/northeast-clerkships/) are set to not display in navigation
- This only appears on the parent page in the sidebar, but not any of the child pages

**Comment by malakhi** [comment]
upon further inspection it isn't a bug

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Inder Singh** in **#wp-dev**. [View the logs :arrow_right:](https://buweb.slack.com/archives/wp-dev/p1458589654000085)
