### ISSUE TITLE
Accordions broken in WP 5.5+

### ISSUE THREAD

**Issue by jakeatbgohiodotorg** [bu-ist/bu-navigation#67]
Howdy, after upgrading to WP 5.5.1, many accordions on my site are broken. Some don't expand. Others are expanded and never contract. I installed "Enable jQuery Migrate Helper" to figure out why and got the following results on pages with Accordions.

```
jQuery Migrate Helper — Warnings encountered
This page generated the following warnings:

https://www.bgohio.org/wp-content/plugins/bu-navigation/js/bu-navigation.min.js: jQuery.browser is deprecated
https://www.bgohio.org/wp-content/plugins/bu-navigation/js/bu-navigation.min.js: jQuery.browser is deprecated
https://www.bgohio.org/wp-content/plugins/bu-navigation/js/navigation-metabox.min.js: jQuery.fn.attr('checked') might use property instead of attribute
Please make sure you are using the latest version of all of your plugins, and your theme. If you are, you may want to ask the developers of the code mentioned in the warnings for an update.
```

Is there anything I can modify to keep using your plugin on my site? It's incredibly useful!

**Comment by jdub233** [comment]
Hi, thanks for the report.

Have you tried updating to the latest version of the plugin?  As of [release 1.2.20](https://github.com/bu-ist/bu-navigation/releases/tag/1.2.20) the 5.5 compatibility issues should be patched.
