### ISSUE TITLE
Show drafts in page tree

### ISSUE THREAD

**Issue by electricbrick** [bu-ist/bu-navigation#8]
It would be nice if drafts were shown, or if there were a filter to toggle draft visibility, since large hierarchies often require the use of draft pages for previewing, as well as swapping out content from time to time.

**Comment by Quixomatic** [comment]
Was this ever added to the plugin?

**Comment by electricbrick** [comment]
Not that I know of.

**Comment by Quixomatic** [comment]
Don't suppose you ever customized the scripts at all? Going to see what I can change if I have to
