### ISSUE TITLE
missing widget_bu_pages_args filter

### ISSUE THREAD

**Issue by nobleclem** [bu-ist/bu-navigation#95]
It looks like as of v1.2.24 the filter `widget_bu_pages_args` was removed from bu-navigation-widet.php during its rework.

The now newer bu-navigation-core-widget/src/class-navigation-widget.php seems to also be missing this filter.

Any chance on getting the widget args filter added back?

**Comment by jdub233** [comment]
Yes, I think we can restore this filter. I will follow up with a PR.

**Comment by jdub233** [comment]
Filter restored in 1.3.2
